### ISSUE TITLE
UPDATE_SUCCESS results in invalid status

### ISSUE THREAD

**Issue by seblau** [shoutem/redux-io#53]
What is the reason behind setting the status to invalid upon `UPDATE_SUCCESS`? See https://github.com/shoutem/redux-io/blob/67b0717b79a8b8bf2dcbaa05bef63ad0285650dd/src/middlewares/apiStateMiddleware.js#L292

**Comment by damirjuretic** [comment]
Hi @seblau, the reason behind setting the status to invalid upon UPDATE_SUCCESS is that we can't know which references of that item being updated need to be invalidated so we are invalidating all of them.

Let's take for example collection of some items ordered by the updated date. If you update an item from that collection order of items in that collection needs to be updated (reloaded again) as we can't know which collection should be invalidated a which not we are invalidating all of them.

We have introduced in the latest release(3.2.2) an option to pass a param to actions like "find", "create", "update" and "remove" so that user can control when references should be invalidated. Example of an action:
```
update(config, item, params, { invalidateReferences: false })
```
